import init, { generate } from "./pkg/word_deck.js";
import { requestFromValues } from "./request.js";

const form = document.querySelector("#generator");
const status = document.querySelector("#status");

function download(content, filename, mime) {
  const link = document.createElement("a");
  link.href = URL.createObjectURL(new Blob([content], { type: mime }));
  link.download = filename;
  link.click();
  setTimeout(() => URL.revokeObjectURL(link.href), 0);
}

async function exportPdf(typst) {
  try {
    const { $typst } = await import("https://esm.sh/@myriaddreamin/typst.ts@0.7.0");
    const pdf = await $typst.pdf({ mainContent: typst });
    download(pdf, "word-deck.pdf", "application/pdf");
    return "Downloaded PDF generated by Typst WASM.";
  } catch (error) {
    download(typst, "word-deck.typ", "text/plain;charset=utf-8");
    return `Typst PDF compiler was unavailable (${error.message}); downloaded Typst source instead.`;
  }
}

await init();
status.textContent = "Ready.";

form.addEventListener("submit", async (event) => {
  event.preventDefault();
  const values = Object.fromEntries(new FormData(form));
  const request = requestFromValues(values);
  try {
    status.textContent = "Generating…";
    if (request.format === "pdf") {
      request.format = "typst";
      const response = JSON.parse(generate(JSON.stringify(request)));
      status.textContent = await exportPdf(response.content);
      return;
    }
    const response = JSON.parse(generate(JSON.stringify(request)));
    const mime = response.format === "html" ? "text/html;charset=utf-8" : "text/plain;charset=utf-8";
    download(response.content, `word-deck.${response.format}`, mime);
    status.textContent = `Downloaded ${response.cards.length} cards as ${response.format.toUpperCase()}.`;
  } catch (error) {
    status.textContent = `Could not generate deck: ${error.message}`;
  }
});
