export async function compilePdf(typst, compiler, download) {
  try {
    const pdf = await compiler(typst);
    download(pdf, "word-deck.pdf", "application/pdf");
    return { ok: true, message: "Downloaded PDF generated by Typst WASM." };
  } catch (error) {
    return { ok: false, message: `Typst PDF compiler was unavailable: ${error.message}` };
  }
}
